name: Build and Push to ECR

on:
  push:
    branches:
      - main # main 브랜치로 푸시될 때 트리거

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. AWS 로그인
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # 3. Docker 이미지 빌드
      - name: Build Docker image
        run: |
          docker build -t flask-app:latest .

      # 4. 태그 지정
      - name: Tag Docker image
        run: |
          docker tag flask-app:latest <AWS_ECR_URI>/flask-app:latest

      # 5. Docker 이미지 푸시
      - name: Push to Amazon ECR
        run: |
          docker push <AWS_ECR_URI>/flask-app:latest
